server:
  port: 8082
  
open-weather:
  api:
    url: https://api.openweathermap.org/data/2.5/weather
    units: metric
    app-id: 5b9e49bdc368b5bfaa5d096faaf3fd71

spotify:
  api:
    suggestionUrl: https://api.spotify.com/v1/recommendations
    tokenUrl: https://accounts.spotify.com/api/token
    clientId: 3e4985444812493a806352b749b77fde
    clientSecret: 3ac84241b00944d29e81cd5eb62f0fd9

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  cache:
    type: redis
    redis:
      time-to-live: 60000
      maxmemory: 128mb

redis:
  host: localhost
  port: 6379
